### Настройки MAVEN ###
maven:
  settings_id: "settings"
  home: "Maven 3.9.6"
  jdk: "openjdk-21"
  use_for_deploy: true

### Настройки NodeJS ###
npm:
  config_id: "npm_config"
  version: "v20.9.0-linux-x64"

### Свойства вашего дистрибутива ###
fp:
  groupId: "io.github.ObraztsovOleg"
  artifactId: "efs-devops-pipeline" ## КЭ для которого есть область в  https://sbrf-nexus.sigma.sbrf.ru/nexus/
  version: "D-1.0.0" # любая
  component_code: cije

bh:
  - name: test.app.backend.sonar
    repo: ssh://git@github.com/ObraztsovOleg/test.backend.git
    branch: master
    cmd:
      - "clean install -U -P build-config,spring"
    sonarPomConfigured: false
    sonarSkip: true
    create_tag: false
    outputs: [
        "target/*.war"
    ]
    update_version: false
    skip_rn: true

build:
  node.sbom.sample:
    builder: npm
    repo: ssh://git@github.com/ObraztsovOleg/HW02_app_IOT.git
    branch: main
    install: "npm ci --ignore-scripts --no-audit --no-fund"
    cmd: "node -e \"JSON.parse(require('fs').readFileSync('package.json', 'utf8')); console.log('node sbom sample ok')\""
    outputs:
      - source: "package.json"
        dest: "pl/node.sbom.sample"
    update_version: false
    create_tag: false
    sonarSkip: true
    skip_rn: true

  go.sbom.sample:
    builder: jenkinsfile
    repo: ssh://git@github.com/spf13/cobra.git
    branch: main
    skip: true
    update_version: false
    create_tag: false
    sonarSkip: true
    skip_rn: true

  python.sbom.sample:
    builder: jenkinsfile
    repo: ssh://git@github.com/ObraztsovOleg/demo.config.git
    branch: sbom-go-node-test
    script_path: Jenkinsfile
    update_version: false
    create_tag: false
    sonarSkip: true
    skip_rn: true
    
nexus:
  creds: "deploy-creds" # id (создадим позже) ТУЗа, c доступом на чтение из:
  use_maven: true


distribution:
  - type: maven
    url: "https://maven.pkg.github.com/ObraztsovOleg/maven"
    serverId: "nexus_cd"

qgm:
  repository: "Nexus_PROD"
  creds: "deploy-creds"

### Настройки сборки Dockerfile ###
docker:
  builder_token: "deploy-docker" # id ТУЗа с доступ на запись в nexus3
  registry_address: "docker.io"
  nexus_url: "k32nc23423" # путь до вашей области с образами
  additional_registries:
    - "https://index.docker.io/v1/"

extensions:
  - name: testSBOM
    repo: ssh://git@github.com/ObraztsovOleg/demo.config.git
    branch: master
    script_path: generateSBOMCyclonedxNexus.groovy
    stage: build
    phase: after
    cdxgen: cdxgen-12.6.0
    cdxgen_path: cdxgen
    cyclonedx_cli: cyclonedx-cli-0.32.0
    cyclonedx_cli_path: cyclonedx
    parallel: false
    args:
      - "-t java"
      - "-t jar"
      - "-t js"
      - "-t go"
      - "-t python"

disabled_extensions:
  - "makeReleaseNotes"
  - "uploadQGFlags"
  - "updateVersionConf"
  - "analyzeDependencies"
